/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import Controlador.*;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author alemayhua
 */
public class VistaSupervisorLinea extends javax.swing.JFrame {

    /**
     * Creates new form VistaSupervisorLinea
     */
    public VistaSupervisorLinea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGrupo = new javax.swing.ButtonGroup();
        pnlOpciones = new javax.swing.JPanel();
        rbtnCrearOP = new javax.swing.JRadioButton();
        rbtnGestionarModelos = new javax.swing.JRadioButton();
        rbtnGestionarColores = new javax.swing.JRadioButton();
        btnCerrarSesion = new javax.swing.JButton();
        pnlTablaOP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOP = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblSupervisor = new javax.swing.JLabel();
        pnlCrearOP = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblEstadoOP = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        pnlModelo = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbDenominacionModelo = new javax.swing.JComboBox<>();
        lblSKUModelo = new javax.swing.JLabel();
        btnPausar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        pnlLinea = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbNumeroLinea = new javax.swing.JComboBox<>();
        lblDescripcionLinea = new javax.swing.JLabel();
        pnlColor = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbDescripcionColor = new javax.swing.JComboBox<>();
        lblCodigoColor = new javax.swing.JLabel();
        lblNumeroOP = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlGestionarModelos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnAgregarModelo = new javax.swing.JButton();
        txtDenominacionModelo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblModelos = new javax.swing.JTable();
        btnBorrarModelo = new javax.swing.JButton();
        txtSKUModelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlGestionarColores = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnAgregarColor = new javax.swing.JButton();
        txtDescripcionColor = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblColores = new javax.swing.JTable();
        btnBorrarColor = new javax.swing.JButton();
        txtCodigoColor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlOpciones.setPreferredSize(new java.awt.Dimension(270, 130));
        pnlOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtnGrupo.add(rbtnCrearOP);
        rbtnCrearOP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnCrearOP.setText("OP");
        rbtnCrearOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCrearOPActionPerformed(evt);
            }
        });
        pnlOpciones.add(rbtnCrearOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        rbtnGrupo.add(rbtnGestionarModelos);
        rbtnGestionarModelos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnGestionarModelos.setText("Gestionar Modelos");
        rbtnGestionarModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGestionarModelosActionPerformed(evt);
            }
        });
        pnlOpciones.add(rbtnGestionarModelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        rbtnGrupo.add(rbtnGestionarColores);
        rbtnGestionarColores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnGestionarColores.setText("Gestionar Colores");
        rbtnGestionarColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGestionarColoresActionPerformed(evt);
            }
        });
        pnlOpciones.add(rbtnGestionarColores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, 200, 40));

        pnlTablaOP.setPreferredSize(new java.awt.Dimension(270, 130));
        pnlTablaOP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setFocusable(false);

        tblOP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N° OP", "Fecha", "Estado", "Linea", "Modelo", "Color", "Supervisor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOP.setEnabled(false);
        tblOP.setFocusable(false);
        jScrollPane1.setViewportView(tblOP);
        if (tblOP.getColumnModel().getColumnCount() > 0) {
            tblOP.getColumnModel().getColumn(0).setResizable(false);
            tblOP.getColumnModel().getColumn(1).setResizable(false);
            tblOP.getColumnModel().getColumn(2).setResizable(false);
            tblOP.getColumnModel().getColumn(3).setResizable(false);
            tblOP.getColumnModel().getColumn(4).setResizable(false);
            tblOP.getColumnModel().getColumn(5).setResizable(false);
            tblOP.getColumnModel().getColumn(6).setResizable(false);
        }

        pnlTablaOP.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 80));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Empleado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 36, -1, -1));
        jPanel1.add(lblEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 36, 100, -1));

        jLabel3.setText("DNI:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 64, -1, -1));
        jPanel1.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 64, 100, -1));

        jLabel5.setText("Correo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 92, -1, -1));
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 92, 100, -1));

        lblSupervisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 185, -1));

        pnlCrearOP.setBackground(new java.awt.Color(0, 102, 102));
        pnlCrearOP.setPreferredSize(new java.awt.Dimension(270, 130));
        pnlCrearOP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha:");
        pnlCrearOP.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, 20));

        lblEstadoOP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstadoOP.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoOP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlCrearOP.add(lblEstadoOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 250, -1));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        pnlCrearOP.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 100, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("N° de Orden:");
        pnlCrearOP.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 20));

        btnFinalizar.setText("Finalizar");
        btnFinalizar.setEnabled(false);
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        pnlCrearOP.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 120, 40));

        pnlModelo.setBackground(new java.awt.Color(0, 102, 102));
        pnlModelo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MODELO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlModelo.setToolTipText("");
        pnlModelo.setName(""); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("SKU:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Denominación:");

        cbDenominacionModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDenominacionModeloActionPerformed(evt);
            }
        });

        lblSKUModelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSKUModelo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlModeloLayout = new javax.swing.GroupLayout(pnlModelo);
        pnlModelo.setLayout(pnlModeloLayout);
        pnlModeloLayout.setHorizontalGroup(
            pnlModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModeloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModeloLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSKUModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlModeloLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDenominacionModelo, 0, 107, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlModeloLayout.setVerticalGroup(
            pnlModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModeloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbDenominacionModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblSKUModelo))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlCrearOP.add(pnlModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 230, 100));

        btnPausar.setText("⏸️ ︎Pausar");
        btnPausar.setEnabled(false);
        btnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausarActionPerformed(evt);
            }
        });
        pnlCrearOP.add(btnPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 120, 40));

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        pnlCrearOP.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 340, 120, 40));

        pnlLinea.setBackground(new java.awt.Color(0, 102, 102));
        pnlLinea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LÍNEA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Descripción:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Número:");

        cbNumeroLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNumeroLineaActionPerformed(evt);
            }
        });

        lblDescripcionLinea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescripcionLinea.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlLineaLayout = new javax.swing.GroupLayout(pnlLinea);
        pnlLinea.setLayout(pnlLineaLayout);
        pnlLineaLayout.setHorizontalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLineaLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcionLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNumeroLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlLineaLayout.setVerticalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLineaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbNumeroLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblDescripcionLinea))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlCrearOP.add(pnlLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 230, 100));

        pnlColor.setBackground(new java.awt.Color(0, 102, 102));
        pnlColor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COLOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Código:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Descripción:");

        cbDescripcionColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDescripcionColorActionPerformed(evt);
            }
        });

        lblCodigoColor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodigoColor.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlColorLayout = new javax.swing.GroupLayout(pnlColor);
        pnlColor.setLayout(pnlColorLayout);
        pnlColorLayout.setHorizontalGroup(
            pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDescripcionColor, 0, 125, Short.MAX_VALUE)
                    .addGroup(pnlColorLayout.createSequentialGroup()
                        .addComponent(lblCodigoColor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlColorLayout.setVerticalGroup(
            pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cbDescripcionColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lblCodigoColor))
                .addGap(32, 32, 32))
        );

        pnlCrearOP.add(pnlColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 230, 100));

        lblNumeroOP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumeroOP.setForeground(new java.awt.Color(255, 255, 255));
        pnlCrearOP.add(lblNumeroOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 100, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ORDEN DE PRODUCCIÓN");
        pnlCrearOP.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 10, 250, -1));

        pnlGestionarModelos.setBackground(new java.awt.Color(0, 102, 102));
        pnlGestionarModelos.setPreferredSize(new java.awt.Dimension(270, 130));
        pnlGestionarModelos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("GESTION DE MODELOS");
        pnlGestionarModelos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 250, -1));

        btnAgregarModelo.setText("Agregar");
        btnAgregarModelo.setEnabled(false);
        btnAgregarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarModeloActionPerformed(evt);
            }
        });
        pnlGestionarModelos.add(btnAgregarModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 50));

        txtDenominacionModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDenominacionModeloKeyReleased(evt);
            }
        });
        pnlGestionarModelos.add(txtDenominacionModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 80, -1));

        tblModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "SKU", "Denominación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblModelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblModelosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblModelos);
        if (tblModelos.getColumnModel().getColumnCount() > 0) {
            tblModelos.getColumnModel().getColumn(0).setResizable(false);
            tblModelos.getColumnModel().getColumn(0).setPreferredWidth(3);
            tblModelos.getColumnModel().getColumn(1).setResizable(false);
        }

        pnlGestionarModelos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 390, 140));

        btnBorrarModelo.setText("Borrar");
        btnBorrarModelo.setEnabled(false);
        btnBorrarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarModeloActionPerformed(evt);
            }
        });
        pnlGestionarModelos.add(btnBorrarModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 250, 40));

        txtSKUModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSKUModeloKeyReleased(evt);
            }
        });
        pnlGestionarModelos.add(txtSKUModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 80, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Denominación");
        pnlGestionarModelos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SKU");
        pnlGestionarModelos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 20));

        pnlGestionarColores.setBackground(new java.awt.Color(0, 102, 102));
        pnlGestionarColores.setPreferredSize(new java.awt.Dimension(270, 130));
        pnlGestionarColores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("GESTION DE COLORES");
        pnlGestionarColores.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 250, -1));

        btnAgregarColor.setText("Agregar");
        btnAgregarColor.setEnabled(false);
        btnAgregarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarColorActionPerformed(evt);
            }
        });
        pnlGestionarColores.add(btnAgregarColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 50));

        txtDescripcionColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionColorKeyReleased(evt);
            }
        });
        pnlGestionarColores.add(txtDescripcionColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 80, -1));

        tblColores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblColores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblColoresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblColores);
        if (tblColores.getColumnModel().getColumnCount() > 0) {
            tblColores.getColumnModel().getColumn(0).setResizable(false);
            tblColores.getColumnModel().getColumn(0).setPreferredWidth(3);
            tblColores.getColumnModel().getColumn(1).setResizable(false);
        }

        pnlGestionarColores.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 390, 140));

        btnBorrarColor.setText("Borrar");
        btnBorrarColor.setEnabled(false);
        btnBorrarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarColorActionPerformed(evt);
            }
        });
        pnlGestionarColores.add(btnBorrarColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 250, 40));

        txtCodigoColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoColorKeyReleased(evt);
            }
        });
        pnlGestionarColores.add(txtCodigoColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 80, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descripción");
        pnlGestionarColores.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Código");
        pnlGestionarColores.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(589, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(252, Short.MAX_VALUE)
                    .addComponent(pnlGestionarColores, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(252, Short.MAX_VALUE)
                    .addComponent(pnlCrearOP, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(252, Short.MAX_VALUE)
                    .addComponent(pnlGestionarModelos, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlTablaOP, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(589, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(379, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlGestionarColores, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(104, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlCrearOP, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(104, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlGestionarModelos, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(104, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(427, Short.MAX_VALUE)
                    .addComponent(pnlTablaOP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(152, Short.MAX_VALUE)
                    .addComponent(pnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(105, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnCrearOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCrearOPActionPerformed
        // TODO add your handling code here:
        ControladorSupervisorLinea.botonRadioOP();
    }//GEN-LAST:event_rbtnCrearOPActionPerformed

    private void rbtnGestionarColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGestionarColoresActionPerformed
        // TODO add your handling code here:
        ControladorSupervisorLinea.botonRadioGestionarColores();
    }//GEN-LAST:event_rbtnGestionarColoresActionPerformed

    private void rbtnGestionarModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGestionarModelosActionPerformed
        // TODO add your handling code here:
        ControladorSupervisorLinea.botonRadioGestionarModelos();
    }//GEN-LAST:event_rbtnGestionarModelosActionPerformed

    private void btnAgregarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarModeloActionPerformed
        // TODO add your handling code here:
        ControladorModeloColor.botonAgregar(txtSKUModelo, txtDenominacionModelo, btnAgregarModelo);
    }//GEN-LAST:event_btnAgregarModeloActionPerformed

    private void btnAgregarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarColorActionPerformed
        // TODO add your handling code here:
        ControladorModeloColor.botonAgregar(txtCodigoColor, txtDescripcionColor, btnAgregarColor);
    }//GEN-LAST:event_btnAgregarColorActionPerformed

    private void btnBorrarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarColorActionPerformed
        // TODO add your handling code here:
        ControladorModeloColor.botonBorrar(tblColores);
    }//GEN-LAST:event_btnBorrarColorActionPerformed

    private void txtSKUModeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSKUModeloKeyReleased
        // TODO add your handling code here:
        ControladorModeloColor.habilitarBotonAgregar(txtSKUModelo, txtDenominacionModelo, btnAgregarModelo);
    }//GEN-LAST:event_txtSKUModeloKeyReleased

    private void txtDenominacionModeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDenominacionModeloKeyReleased
        // TODO add your handling code here:
        ControladorModeloColor.habilitarBotonAgregar(txtSKUModelo, txtDenominacionModelo, btnAgregarModelo);
    }//GEN-LAST:event_txtDenominacionModeloKeyReleased

    private void txtCodigoColorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoColorKeyReleased
        // TODO add your handling code here:
        ControladorModeloColor.habilitarBotonAgregar(txtCodigoColor, txtDescripcionColor, btnAgregarColor);
    }//GEN-LAST:event_txtCodigoColorKeyReleased

    private void txtDescripcionColorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionColorKeyReleased
        // TODO add your handling code here:
        ControladorModeloColor.habilitarBotonAgregar(txtCodigoColor, txtDescripcionColor, btnAgregarColor);
    }//GEN-LAST:event_txtDescripcionColorKeyReleased

    private void tblModelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblModelosMouseClicked
        // TODO add your handling code here:
        ControladorModeloColor.habilitarBotonBorrar(tblModelos, btnBorrarModelo);
    }//GEN-LAST:event_tblModelosMouseClicked

    private void tblColoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblColoresMouseClicked
        // TODO add your handling code here:
        ControladorModeloColor.habilitarBotonBorrar(tblColores, btnBorrarColor);
    }//GEN-LAST:event_tblColoresMouseClicked

    private void btnBorrarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarModeloActionPerformed
        // TODO add your handling code here:
        ControladorModeloColor.botonBorrar(tblModelos);
    }//GEN-LAST:event_btnBorrarModeloActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        ControladorOP.botonFinalizarOP();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausarActionPerformed
        // TODO add your handling code here:
        ControladorOP.botonPausarOP();
    }//GEN-LAST:event_btnPausarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        ControladorOP.botonInciarOP();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void cbNumeroLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNumeroLineaActionPerformed
        // TODO add your handling code here:
        ControladorOP.llenarLabels(cbNumeroLinea);
    }//GEN-LAST:event_cbNumeroLineaActionPerformed

    private void cbDenominacionModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDenominacionModeloActionPerformed
        // TODO add your handling code here:
        ControladorOP.llenarLabels(cbDenominacionModelo);
    }//GEN-LAST:event_cbDenominacionModeloActionPerformed

    private void cbDescripcionColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDescripcionColorActionPerformed
        // TODO add your handling code here:
        ControladorOP.llenarLabels(cbDescripcionColor);
    }//GEN-LAST:event_cbDescripcionColorActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        ControladorInicio.botonCerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSupervisorLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSupervisorLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSupervisorLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSupervisorLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSupervisorLinea().setVisible(true);
            }
        });
    }

    public JLabel getLblFecha() {
        return lblFecha;
    }

    public JLabel getLblNumeroOP() {
        return lblNumeroOP;
    }

    public JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }

    public JLabel getLblCorreo() {
        return lblCorreo;
    }

    public JLabel getLblDni() {
        return lblDni;
    }

    public JLabel getLblEmpleado() {
        return lblEmpleado;
    }

    public JLabel getLblSupervisor() {
        return lblSupervisor;
    }

    public JPanel getPnlCrearOP() {
        return pnlCrearOP;
    }

    public JPanel getPnlGestionarColores() {
        return pnlGestionarColores;
    }

    public JPanel getPnlGestionarModelos() {
        return pnlGestionarModelos;
    }

    public JRadioButton getRbtnCrearOP() {
        return rbtnCrearOP;
    }

    public JRadioButton getRbtnGestionarColores() {
        return rbtnGestionarColores;
    }

    public JRadioButton getRbtnGestionarModelos() {
        return rbtnGestionarModelos;
    }

    public ButtonGroup getRbtnGrupo() {
        return rbtnGrupo;
    }

    public JTable getTblColores() {
        return tblColores;
    }

    public JTable getTblModelos() {
        return tblModelos;
    }

    public JTextField getTxtCodigoColor() {
        return txtCodigoColor;
    }

    public JTextField getTxtDenominacionModelo() {
        return txtDenominacionModelo;
    }

    public JTextField getTxtDescripcionColor() {
        return txtDescripcionColor;
    }

    public JTextField getTxtSKUModelo() {
        return txtSKUModelo;
    }

    public JButton getBtnAgregarColor() {
        return btnAgregarColor;
    }

    public JButton getBtnAgregarModelo() {
        return btnAgregarModelo;
    }

    public JButton getBtnBorrarColor() {
        return btnBorrarColor;
    }

    public JButton getBtnBorrarModelo() {
        return btnBorrarModelo;
    }

    public JComboBox<String> getCbDenominacionModelo() {
        return cbDenominacionModelo;
    }

    public JComboBox<String> getCbDescripcionColor() {
        return cbDescripcionColor;
    }

    public JComboBox<String> getCbNumeroLinea() {
        return cbNumeroLinea;
    }

    public JLabel getLblCodigoColor() {
        return lblCodigoColor;
    }

    public JLabel getLblDescripcionLinea() {
        return lblDescripcionLinea;
    }

    public JLabel getLblSKUModelo() {
        return lblSKUModelo;
    }

    public JButton getBtnFinalizar() {
        return btnFinalizar;
    }

    public JButton getBtnIniciar() {
        return btnIniciar;
    }

    public JButton getBtnPausar() {
        return btnPausar;
    }

    public JLabel getLblEstadoOP() {
        return lblEstadoOP;
    }

    public JTable getTblOP() {
        return tblOP;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarColor;
    private javax.swing.JButton btnAgregarModelo;
    private javax.swing.JButton btnBorrarColor;
    private javax.swing.JButton btnBorrarModelo;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPausar;
    private javax.swing.JComboBox<String> cbDenominacionModelo;
    private javax.swing.JComboBox<String> cbDescripcionColor;
    private javax.swing.JComboBox<String> cbNumeroLinea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCodigoColor;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDescripcionLinea;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblEstadoOP;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNumeroOP;
    private javax.swing.JLabel lblSKUModelo;
    private javax.swing.JLabel lblSupervisor;
    private javax.swing.JPanel pnlColor;
    private javax.swing.JPanel pnlCrearOP;
    private javax.swing.JPanel pnlGestionarColores;
    private javax.swing.JPanel pnlGestionarModelos;
    private javax.swing.JPanel pnlLinea;
    private javax.swing.JPanel pnlModelo;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlTablaOP;
    private javax.swing.JRadioButton rbtnCrearOP;
    private javax.swing.JRadioButton rbtnGestionarColores;
    private javax.swing.JRadioButton rbtnGestionarModelos;
    private javax.swing.ButtonGroup rbtnGrupo;
    private javax.swing.JTable tblColores;
    private javax.swing.JTable tblModelos;
    private javax.swing.JTable tblOP;
    private javax.swing.JTextField txtCodigoColor;
    private javax.swing.JTextField txtDenominacionModelo;
    private javax.swing.JTextField txtDescripcionColor;
    private javax.swing.JTextField txtSKUModelo;
    // End of variables declaration//GEN-END:variables
}
